name: second_workflow

on: push

# parallel execution and sequential execution

jobs:
    create_user:
        runs-on: ubuntu-latest
        steps:
            - name: first step of creating a user
              run: exit 1
    
    verify_user:
        runs-on: ubuntu-latest
        needs: [create_user]
        steps:
            - name: this step is to authenticate user.
              run: echo "user verified"